//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spartacus.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spartacus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///%_PRAGMA_COMMENTS_%
        ///
        ///#include &quot;windows.h&quot;
        ///#include &quot;ios&quot;
        ///#include &quot;fstream&quot;
        ///
        ///%_TYPEDEF_%
        ///
        ///HMODULE hModule = LoadLibrary(L&quot;%_REAL_DLL_%&quot;);
        ///
        ///BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
        ///{
        ///    switch (ul_reason_for_call)
        ///    {
        ///    case DLL_PROCESS_ATTACH:
        ///    case DLL_THREAD_ATTACH:
        ///    case DLL_THREAD_DETACH:
        ///    case DLL_PROCESS_DETACH:
        ///        break;
        ///    }
        ///    return TRUE;
        ///}
        ///
        ///VOID DebugToFile(LPCSTR szInput)
        ///{
        ///    std::ofstream [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dllmain_cpp {
            get {
                return ResourceManager.GetString("dllmain.cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// *  This file has been created by using the existing Ghidra ExportFunctionInfoScript.java script as a guide.
        /// *  One would ask &quot;Why don&apos;t you save this output as JSON? Wouldn&apos;t that be easier?&quot; And the answer is &quot;yes, it would be&quot;,
        /// *  however I want to keep Spartacus a standalone executable, and adding a NuGet package for JSON would break that.
        /// */
        ///
        ///import java.util.*;
        ///import java.nio.file.Files;
        ///import java.nio.file.Paths;
        ///import java.nio.charset.Charset;
        ///
        ///import ghidra.app.script.GhidraScri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportFunctionDefinitionsINI_java {
            get {
                return ResourceManager.GetString("ExportFunctionDefinitionsINI.java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #pragma once
        ///
        ///%_PRAGMA_COMMENTS_%
        ///
        ///#include &lt;windows.h&gt;
        ///
        ///VOID Payload() {
        ///    // Run your payload here.
        ///}
        ///
        ///BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved)
        ///{
        ///    switch (fdwReason)
        ///    {
        ///    case DLL_PROCESS_ATTACH:
        ///        Payload();
        ///        break;
        ///    case DLL_THREAD_ATTACH:
        ///        break;
        ///    case DLL_THREAD_DETACH:
        ///        break;
        ///    case DLL_PROCESS_DETACH:
        ///        break;
        ///    }
        ///    return TRUE;
        ///}.
        /// </summary>
        internal static string proxy_dll_cpp {
            get {
                return ResourceManager.GetString("proxy.dll.cpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio Version 17
        ///VisualStudioVersion = 17.4.33213.308
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}&quot;) = &quot;proxy&quot;, &quot;proxy.vcxproj&quot;, &quot;{6FCED408-75B2-4EF9-9E5F-3EC58B19249B}&quot;
        ///EndProject
        ///Global
        ///	GlobalSection(SolutionConfigurationPlatforms) = preSolution
        ///		Debug|x64 = Debug|x64
        ///		Debug|x86 = Debug|x86
        ///		Release|x64 = Release|x64
        ///		Release|x86 = Release|x86
        ///	EndGlobalSection
        ///	GlobalSectio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string proxy_sln {
            get {
                return ResourceManager.GetString("proxy.sln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;ItemGroup Label=&quot;ProjectConfigurations&quot;&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Debug|Win32&quot;&gt;
        ///      &lt;Configuration&gt;Debug&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///    &lt;ProjectConfiguration Include=&quot;Release|Win32&quot;&gt;
        ///      &lt;Configuration&gt;Release&lt;/Configuration&gt;
        ///      &lt;Platform&gt;Win32&lt;/Platform&gt;
        ///    &lt;/ProjectConfiguration&gt;
        ///    &lt;ProjectCon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string proxy_vcxproj {
            get {
                return ResourceManager.GetString("proxy.vcxproj", resourceCulture);
            }
        }
    }
}
